services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mysql
    ports:
      - 80:80
    restart: always
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_DEBUG: '${WORDPRESS_DEBUG}'
      WORDPRESS_TABLE_PREFIX: '${WORDPRESS_TABLE_PREFIX}'
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('SCRIPT_DEBUG', true);
    volumes:
      - ./.srv/wordpress/:/var/www/html
      - ./.srv/log/:/var/log
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  wpcli:
    container_name: wpcli
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    env_file:
      - ./.env
    entrypoint: wp
    command: "--info"
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_DEBUG: '${WORDPRESS_DEBUG}'
      WORDPRESS_TABLE_PREFIX: '${WORDPRESS_TABLE_PREFIX}'
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
    volumes:
      - ./.srv/wordpress/:/var/www/html
      - ./.srv/log/:/var/log
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - "./.srv/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

